// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "Abebe kassa",
    email: "abebe@kassa.com",
    photo: "/man.png",
    phone: "+251942237570",
    subjects: ["Math", "IT"],
    classes: ["8B", "10A"],
    address: "ayat, Addis Ababa, Ethiopia",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Natnael Tibebu",
    email: "natnael@tibebu.com",
    photo: "/man.png",
    phone: "+251942237570",
    subjects: ["Physics", "Chemistry"],
    classes: ["12A", "9C"],
    address: "ayat, Addis Ababa, Ethiopia",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Abebe kassa",
    email: "abebe@kassa.com",
    photo: "/man.png",
    phone: "+251942237570",
    subjects: ["Biology"],
    classes: ["11A", "12B", "10C"],
    address: "ayat, Addis Ababa, Ethiopia",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Abebe kassa",
    email: "abebe@kassa.com",
    photo: "/man.png",
    phone: "+251942237570",
    subjects: ["Geography"],
    classes: ["10B", "12A"],
    address: "ayat, Addis Ababa, Ethiopia",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Abebe kassa",
    email: "abebe@kassa.com",
    photo: "/man.png",
    phone: "+251942237570",
    subjects: ["Sport", "History"],
    classes: ["7A", "10B", "8C"],
    address: "ayat, Addis Ababa, Ethiopia",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Abebe kassa",
    email: "abebe@kassa.com",
    photo: "/man.png",
    phone: "+251942237570",
    subjects: ["Physics"],
    classes: ["9A", "10B", "10C"],
    address: "ayat, Addis Ababa, Ethiopia",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo: "/man.png",
    phone: "+251942237570",
    subjects: ["English", "Civics"],
    classes: ["8A", "9B", "9C"],
    address: "ayat, Addis Ababa, Ethiopia",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "abebe@kassa.com",
    email: "abebe@kassa.com",
    photo: "/man.png",
    phone: "+251942237570",
    subjects: ["Math", "Geometry"],
    classes: ["7A", "8B", "10C"],
    address: "ayat, Addis Ababa, Ethiopia",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Abebe kassa",
    email: "abebe@kassa.com",
    photo: "/man.png",
    phone: "+251942237570",
    subjects: ["chemistry", "English"],
    classes: ["8A", "10B", "9C"],
    address: "ayat, Addis Ababa, Ethiopia",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "Abebe kassa",
    email: "abebe@kassa.com",
    photo: "/man.png",
    phone: "+251942237570",
    subjects: ["Biology"],
    classes: ["7A", "7B", "10C"],
    address: "ayat, Addis Ababa, Ethiopia",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "Abel beyene",
    email: "abel@beyene.com",
    photo: "/graduate.png",
    phone: "+25142237570",
    grade: 9,
    class: "9B",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Abel beyene",
    email: "abel@beyene.com",
    photo: "/graduate.png",
    phone: "+25142237570",
    grade: 10,
    class: "10A",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Abel beyene",
    email: "abel@beyene.com",
    photo: "/graduate.png",
    phone: "+25142237570",
    grade: 10,
    class: "10C",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Abel beyene",
    email: "abel@beyene.com",
    photo: "/graduate.png",
    phone: "+25142237570",
    grade: 11,
    class: "11A",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Abel beyene",
    email: "abel@beyene.com",
    photo: "/graduate.png",
    phone: "+25142237570",
    grade: 11,
    class: "11C",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Abel beyene",
    email: "abel@beyene.com",
    photo: "/graduate.png",
    phone: "+25142237570",
    grade: 8,
    class: "8A",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Abel beyene",
    email: "abel@beyene.com",
    photo: "/graduate.png",
    phone: "+25142237570",
    grade: 8,
    class: "8B",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Abel beyene",
    email: "abel@beyene.com",
    photo: "/graduate.png",
    phone: "+25142237570",
    grade: 12,
    class: "12A",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Abel beyene",
    email: "abel@beyene.com",
    photo: "/graduate.png",
    phone: "+25142237570",
    grade: 12,
    class: "12B",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "Abel beyene",
    email: "abel@beyene.com",
    photo: "/graduate.png",
    phone: "+25142237570",
    grade: 12,
    class: "12C",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "Beyene Woldie",
    students: ["Abel Beyene"],
    email: "beyene@woldie.com",
    phone: "+25142237570",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
  {
    id: 2,
    name: "Beyene Woldie",
    students: ["Abel Beyene"],
    email: "beyene@woldie.com",
    phone: "+25142237570",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
  {
    id: 3,
    name: "Beyene Woldie",
    students: ["Abel Beyene"],
    email: "beyene@woldie.com",
    phone: "+25142237570",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
  {
    id: 4,
    name: "Beyene Woldie",
    students: ["Abel Beyene"],
    email: "beyene@woldie.com",
    phone: "+25142237570",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
  {
    id: 5,
    name: "Beyene Woldie",
    students: ["Abel Beyene"],
    email: "beyene@woldie.com",
    phone: "+25142237570",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
  {
    id: 6,
    name: "Beyene Woldie",
    students: ["Abel Beyene"],
    email: "beyene@woldie.com",
    phone: "+25142237570",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
  {
    id: 7,
    name: "Beyene Woldie",
    students: ["Abel Beyene"],
    email: "beyene@woldie.com",
    phone: "+25142237570",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
  {
    id: 8,
    name: "Beyene Woldie",
    students: ["Abel Beyene"],
    email: "beyene@woldie.com",
    phone: "+25142237570",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
  {
    id: 9,
    name: "Beyene Woldie",
    students: ["Abel Beyene"],
    email: "beyene@woldie.com",
    phone: "+25142237570",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
  {
    id: 10,
    name: "Beyene Woldie",
    students: ["Abel Beyene"],
    email: "beyene@woldie.com",
    phone: "+25142237570",
    address: "bole, Addis Ababa, Ethiopia   ",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Abebe kassa, Natnael tibebu"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Abebe kassa, Natnael tibebu"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Abebe kassa, Natnael tibebu"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Abebe kassa, Natnael tibebu"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Abebe kassa, Natnael tibebu"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Abebe kassa, Natnael tibebu"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Abebe kassa, Natnael tibebu"],
  },
  {
    id: 8,
    name: "Sport",
    teachers: ["Abebe kassa, Natnael tibebu"],
  },
  {
    id: 9,
    name: "Information technology",
    teachers: ["Abebe kassa, Natnael tibebu"],
  },
  {
    id: 10,
    name: "Civics",
    teachers: ["Abebe kassa, Natnael tibebu"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "8A",
    capacity: 40,
    grade: 8,
    supervisor: "Abebe Kassa",
  },
  {
    id: 2,
    name: "8B",
    capacity: 35,
    grade: 8,
    supervisor: "Natnael Tibebu",
  },
  {
    id: 3,
    name: "9A",
    capacity: 40,
    grade: 9,
    supervisor: "Abebe Kassa",
  },
  {
    id: 4,
    name: "9B",
    capacity: 50,
    grade: 9,
    supervisor: "Natnael Tibebu",
  },
  {
    id: 5,
    name: "10A",
    capacity: 45,
    grade: 10,
    supervisor: "Abebe Kassa",
  },
  {
    id: 6,
    name: "10B",
    capacity: 30,
    grade: 10,
    supervisor: "Natnael Kassa",
  },
  {
    id: 7,
    name: "10C",
    capacity: 25,
    grade: 10,
    supervisor: "Abebe Kassa",
  },
  {
    id: 8,
    name: "11A",
    capacity: 40,
    grade: 11,
    supervisor: "Natnael Tibebu",
  },
  {
    id: 9,
    name: "11B",
    capacity: 40,
    grade: 11,
    supervisor: "Abebe Kassa",
  },
  {
    id: 10,
    name: "12A",
    capacity: 50,
    grade: 12,
    supervisor: "Natnael Tibebu",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "8A",
    teacher: "Abebe Kassa",
  },
  {
    id: 2,
    subject: "English",
    class: "10A",
    teacher: "Natnael Tibebu",
  },
  {
    id: 3,
    subject: "Biology",
    class: "9A",
    teacher: "Abebe Kassa",
  },
  {
    id: 4,
    subject: "Chemistry",
    class: "8B",
    teacher: "Natnael Tibebu",
  },
  {
    id: 5,
    subject: "IT",
    class: "11A",
    teacher: "Abebe Kassa",
  },
  {
    id: 6,
    subject: "Geography",
    class: "10C",
    teacher: "Natnael Tibebu",
  },
  {
    id: 7,
    subject: "History",
    class: "12A",
    teacher: "Abebe Kassa",
  },
  {
    id: 8,
    subject: "Physics",
    class: "10B",
    teacher: "Natnael Tibebu",
  },
  {
    id: 9,
    subject: "Sport",
    class: "8C",
    teacher: "Abebe Kassa",
  },
  {
    id: 10,
    subject: "Civics",
    class: "11B",
    teacher: "Natnael Tibebu",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "8A",
    teacher: "Abebe Kassa",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "10A",
    teacher: "Natnael Tibebu",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Chemistry",
    class: "9A",
    teacher: "Abebe Kassa",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "IT",
    class: "10B",
    teacher: "Natnael Tibebu",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Biology",
    class: "12A",
    teacher: "Abebe Kassa",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "History",
    class: "10C",
    teacher: "Natnael Tibebu",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "Sport",
    class: "10B",
    teacher: "Abebe Kassa",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Birhanu Nega",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "12A",
    teacher: "Natnael Tibebu",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Abebe Kassa",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "8A",
    teacher: "Abebe Kassa",
    dueDate: "2025-02-01",
  },
  {
    id: 2,
    subject: "English",
    class: "9A",
    teacher: "Natnael Tibebu",
    dueDate: "2025-02-01",
  },
  {
    id: 3,
    subject: "Biology",
    class: "10A",
    teacher: "Abebe Kassa",
    dueDate: "2025-02-01",
  },
  {
    id: 4,
    subject: "Chemistry",
    class: "9B",
    teacher: "Natnael Tibebu",
    dueDate: "2025-02-01",
  },
  {
    id: 5,
    subject: "IT",
    class: "12A",
    teacher: "Abebe Kassa",
    dueDate: "2025-02-01",
  },
  {
    id: 6,
    subject: "History",
    class: "9B",
    teacher: "Birhanu Nega",
    dueDate: "2025-02-01",
  },
  {
    id: 7,
    subject: "Geography",
    class: "10A",
    teacher: "Natnael Tibebu",
    dueDate: "2025-02-03",
  },
  {
    id: 8,
    subject: "Physics",
    class: "11B",
    teacher: "Abebe Kassa",
    dueDate: "2025-02-03",
  },
  {
    id: 9,
    subject: "Civics",
    class: "12A",
    teacher: "Natnael Tibebu",
    dueDate: "2025-02-04",
  },
  {
    id: 10,
    subject: "Sport",
    class: "8A",
    teacher: "Abebe Kassa",
    dueDate: "2025-02-03",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "9A",
    teacher: "Natnael Tibebu",
    student: "Abel Beyene",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "10A",
    teacher: "Abebe Kassa",
    student: "Saron Wondimu",
    date: "2025-01-01",
    type: "exam",
    score: 70,
  },
  {
    id: 3,
    subject: "Biology",
    class: "10A",
    teacher: "Daniel Mitiku",
    student: "Hassen Abdu",
    date: "2025-01-01",
    type: "exam",
    score: 85,
  },
  {
    id: 4,
    subject: "Physics",
    class: "11B",
    teacher: "Mulat Dagne",
    student: "Tensay girma",
    date: "2025-01-01",
    type: "exam",
    score: 60,
  },
  {
    id: 5,
    subject: "Chemistry",
    class: "12A",
    teacher: "Yonas Ermiyas",
    student: "Yabsira ketema",
    date: "2025-02-01",
    type: "exam",
    score: 100,
  },
  {
    id: 6,
    subject: "History",
    class: "9A",
    teacher: "Wondossen Getachew",
    student: "Ashenafi wogayew",
    date: "2025-01-01",
    type: "exam",
    score: 70,
  },
  {
    id: 7,
    subject: "IT",
    class: "11A",
    teacher: "Bizuayew Taddese",
    student: "Biruk Belihu",
    date: "2025-01-01",
    type: "exam",
    score: 84,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Dagim Asteray",
    student: "Semira Shafi",
    date: "2025-01-01",
    type: "exam",
    score: 50,
  },
  {
    id: 9,
    subject: "Sport",
    class: "10B",
    teacher: "Bayu Balcha",
    student: "Tsion Wondimu",
    date: "2025-01-01",
    type: "exam",
    score: 70,
  },
  {
    id: 10,
    subject: "Civics",
    class: "8A",
    teacher: "Abel Eyasu",
    student: "Gedion Adugna",
    date: "2025-01-01",
    type: "exam",
    score: 97,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Semester Closing",
    class: "9A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "10A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Color Day",
    class: "11A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "9B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "12A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Debate Tournament",
    class: "10B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "GC birthday",
    class: "12B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Spelling Competition",
    class: "11B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Exhibition Trip",
    class: "9C",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "12A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 9A Math Test",
    class: "9A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 10A Biology Test",
    class: "10A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 10B Math Test",
    class: "10B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 11A Physics Test",
    class: "11A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 9C Chemistry Test",
    class: "9C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 12A English Test",
    class: "11B",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 12B IT Test",
    class: "12B",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 9A Histiory Test",
    class: "9A",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 11C English Test",
    class: "11C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 10A Math Test",
    class: "10C",
    date: "2025-01-01",
  },
];

export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 9, 15, 8, 0),
    end: new Date(2024, 9, 15, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 9, 15, 9, 0),
    end: new Date(2024, 9, 15, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 9, 15, 10, 0),
    end: new Date(2024, 9, 15, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 9, 15, 11, 0),
    end: new Date(2024, 9, 15, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 9, 15, 13, 0),
    end: new Date(2024, 9, 15, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 9, 15, 14, 0),
    end: new Date(2024, 9, 15, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 9, 21, 9, 0),
    end: new Date(2024, 9, 21, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 9, 21, 10, 0),
    end: new Date(2024, 9, 21, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 9, 21, 11, 0),
    end: new Date(2024, 9, 21, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 9, 21, 14, 0),
    end: new Date(2024, 9, 21, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 9, 16, 8, 0),
    end: new Date(2024, 9, 16, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 9, 16, 10, 0),
    end: new Date(2024, 9, 16, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 9, 16, 13, 0),
    end: new Date(2024, 9, 16, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 9, 16, 14, 0),
    end: new Date(2024, 9, 16, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 9, 17, 9, 0),
    end: new Date(2024, 9, 17, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 9, 17, 10, 0),
    end: new Date(2024, 9, 17, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 9, 17, 11, 0),
    end: new Date(2024, 9, 17, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 9, 17, 14, 0),
    end: new Date(2024, 9, 17, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 9, 20, 8, 0),
    end: new Date(2024, 9, 20, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 9, 20, 9, 0),
    end: new Date(2024, 9, 20, 9, 45),
  },

  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 9, 20, 11, 0),
    end: new Date(2024, 9, 20, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 9, 20, 13, 0),
    end: new Date(2024, 9, 20, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 9, 20, 14, 0),
    end: new Date(2024, 9, 20, 14, 45),
  },
];